"""init

Revision ID: 3727d515f88e
Revises: 
Create Date: 2026-09-13 01:09:53.944974

"""
from alembic import op
import sqlalchemy as sa


revision = '3727d515f88e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_level'), 'article', ['level'], unique=False)
    op.create_table('dict_word',
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('phonetic', sa.String(length=128), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.Column('bnc', sa.Integer(), nullable=True),
    sa.Column('frq', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('word')
    )
    op.create_table('word_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('article_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_question_article_id'), 'article_question', ['article_id'], unique=False)
    op.create_table('book_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('phonetic_us', sa.String(length=64), nullable=True),
    sa.Column('phonetic_uk', sa.String(length=64), nullable=True),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['word_book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'word', name='uq_book_word')
    )
    op.create_index(op.f('ix_book_word_book_id'), 'book_word', ['book_id'], unique=False)
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('phonetic', sa.String(length=128), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('ease', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('due', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_review_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['word_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_book_id'), 'card', ['book_id'], unique=False)
    op.create_index(op.f('ix_card_due'), 'card', ['due'], unique=False)
    op.create_index(op.f('ix_card_word'), 'card', ['word'], unique=True)
    op.create_table('reading_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_attempt_article_id'), 'reading_attempt', ['article_id'], unique=False)
    op.create_table('mistake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['article_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mistake_question_id'), 'mistake', ['question_id'], unique=False)
    op.create_index(op.f('ix_mistake_resolved'), 'mistake', ['resolved'], unique=False)
    op.create_table('review_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('prev_interval', sa.Integer(), nullable=False),
    sa.Column('new_interval', sa.Integer(), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_log_card_id'), 'review_log', ['card_id'], unique=False)
    op.create_index(op.f('ix_review_log_study_date'), 'review_log', ['study_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_log_study_date'), table_name='review_log')
    op.drop_index(op.f('ix_review_log_card_id'), table_name='review_log')
    op.drop_table('review_log')
    op.drop_index(op.f('ix_mistake_resolved'), table_name='mistake')
    op.drop_index(op.f('ix_mistake_question_id'), table_name='mistake')
    op.drop_table('mistake')
    op.drop_index(op.f('ix_reading_attempt_article_id'), table_name='reading_attempt')
    op.drop_table('reading_attempt')
    op.drop_index(op.f('ix_card_word'), table_name='card')
    op.drop_index(op.f('ix_card_due'), table_name='card')
    op.drop_index(op.f('ix_card_book_id'), table_name='card')
    op.drop_table('card')
    op.drop_index(op.f('ix_book_word_book_id'), table_name='book_word')
    op.drop_table('book_word')
    op.drop_index(op.f('ix_article_question_article_id'), table_name='article_question')
    op.drop_table('article_question')
    op.drop_table('word_book')
    op.drop_table('dict_word')
    op.drop_index(op.f('ix_article_level'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
