"""add article_sentence

Revision ID: 739e29614dbd
Revises: 3727d515f88e
Create Date: 2026-09-13 02:08:13.294884

"""
from alembic import op
import sqlalchemy as sa


revision = '739e29614dbd'
down_revision = '3727d515f88e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('en', sa.Text(), nullable=False),
    sa.Column('zh', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_sentence_article_id'), 'article_sentence', ['article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_sentence_article_id'), table_name='article_sentence')
    op.drop_table('article_sentence')
    # ### end Alembic commands ###
